//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRM_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Classes = new HashSet<Class>();
        }
    
        public int EmployeeId { get; set; }
        public string EFirstName { get; set; }
        public string ELastName { get; set; }
        public string EAddress { get; set; }
        public string ECity { get; set; }
        public string EProvince { get; set; }
        public string EPhone { get; set; }
        public string ERole { get; set; }
        public string userName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Class> Classes { get; set; }
    }
}
