//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DRM_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DoB { get; set; }
        public string Address { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public Nullable<int> HealthCard { get; set; }
        public string DocName { get; set; }
        public string DocPhone { get; set; }
        public string Comments { get; set; }
    }
}
