//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.Children = new HashSet<Child>();
        }
    
        public int ParentId { get; set; }
        public string PFirstName { get; set; }
        public string PLastName { get; set; }
        public string PAddress { get; set; }
        public string PCity { get; set; }
        public string PProvince { get; set; }
        public string PPhone { get; set; }
        public string userName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Child> Children { get; set; }
    }
}
